//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_KIEM_KE
    {
        public int MaKK { get; set; }
        public int MaTB { get; set; }
        public string NguoiKK { get; set; }
        public string TinhTrang { get; set; }
    
        public virtual KIEM_KE KIEM_KE { get; set; }
        public virtual THIET_BI THIET_BI { get; set; }
    }
}
