//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_SUA_CHUA
    {
        public int MaSC { get; set; }
        public int MaTB { get; set; }
        public string LyDo { get; set; }
        public Nullable<int> ChiPhi { get; set; }
        public string NguoiSC { get; set; }
    
        public virtual SUA_CHUA SUA_CHUA { get; set; }
        public virtual THIET_BI THIET_BI { get; set; }
    }
}
