//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_THU_HOI
    {
        public int MaTH { get; set; }
        public int MaTB { get; set; }
        public string LyDo { get; set; }
    
        public virtual THIET_BI THIET_BI { get; set; }
        public virtual THU_HOI THU_HOI { get; set; }
    }
}
