//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLTHIETBIEntities : DbContext
    {
        public QLTHIETBIEntities()
            : base("name=QLTHIETBIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CAP_PHAT> CAP_PHAT { get; set; }
        public virtual DbSet<CT_CAP_PHAT> CT_CAP_PHAT { get; set; }
        public virtual DbSet<CT_KIEM_KE> CT_KIEM_KE { get; set; }
        public virtual DbSet<CT_SUA_CHUA> CT_SUA_CHUA { get; set; }
        public virtual DbSet<CT_THU_HOI> CT_THU_HOI { get; set; }
        public virtual DbSet<DON_VI> DON_VI { get; set; }
        public virtual DbSet<HANG_SX> HANG_SX { get; set; }
        public virtual DbSet<KIEM_KE> KIEM_KE { get; set; }
        public virtual DbSet<LOAI_THIET_BI> LOAI_THIET_BI { get; set; }
        public virtual DbSet<NHOM_TB> NHOM_TB { get; set; }
        public virtual DbSet<SUA_CHUA> SUA_CHUA { get; set; }
        public virtual DbSet<TANG> TANGs { get; set; }
        public virtual DbSet<THANH_LY> THANH_LY { get; set; }
        public virtual DbSet<THIET_BI> THIET_BI { get; set; }
        public virtual DbSet<THU_HOI> THU_HOI { get; set; }
        public virtual DbSet<TAI_KHOAN> TAI_KHOAN { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
