//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANH_LY
    {
        public int MaTL { get; set; }
        public int MaTB { get; set; }
        public Nullable<System.DateTime> NgayTL { get; set; }
        public string LyDo { get; set; }
        public string NguoiLapPhieu { get; set; }
        public string NguoiPhuTrach { get; set; }
    
        public virtual THIET_BI THIET_BI { get; set; }
    }
}
