//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class THIET_BI
    {
        public int MaTB { get; set; }
        public string TenTB { get; set; }
        public Nullable<int> MaHang { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<int> MaDV { get; set; }
        public Nullable<int> MaLoai { get; set; }
        public Nullable<int> MaTang { get; set; }
        public Nullable<int> ThanhTien { get; set; }
        public Nullable<int> MaTH { get; set; }
        public Nullable<int> MaCP { get; set; }
        public Nullable<int> MaKho { get; set; }
    
        public virtual DON_VI DON_VI { get; set; }
        public virtual HANG_SX HANG_SX { get; set; }
        public virtual KHO KHO { get; set; }
        public virtual LOAI_THIET_BI LOAI_THIET_BI { get; set; }
        public virtual TANG TANG { get; set; }
    }
}
